#!/bin/bash

set -x

LOG_FILE="/var/log/monitoring.log"
STATE_FILE="/var/lib/monitoring/test.pid"
MONITOR_SRV="https://httpbin.org/status/200"

# Поиск процесса
CURRENT_PID=$(pgrep -f "^/bin/bash /usr/local/bin/test ")

if [ -n "$CURRENT_PID" ]; then
  # Процесс запущен

  mkdir -p "$(dirname "$STATE_FILE")"

  if [ -f "$STATE_FILE" ]; then
    LAST_PID=$(cat "$STATE_FILE")
    if [ "$CURRENT_PID" != "$LAST_PID" ]; then
      echo "$(date): Process 'test' was restarted (PID: $CURRENT_PID)" >> "$LOG_FILE"
    fi
  else
    echo "$(date): Process 'test' started (PID: $CURRENT_PID)" >> "$LOG_FILE"
  fi

  # Сохранение PID текущего процесса
  echo "$CURRENT_PID" > "$STATE_FILE"

  # HTTPS-запрос
  if ! curl -sSf "$MONITOR_SRV" > /dev/null; then
    echo "$(date): Failed to reach monitoring API" >> "$LOG_FILE"
  fi
else
  # Процесс не запущен. Удалим файл состояния "STATE_FILE", чтобы разделить перезапуск и запуск процесса
  if [ -f "$STATE_FILE" ]; then
    rm -f "$STATE_FILE"
  fi
fi
